// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// The V8 functions sorted alphabetically

#ifndef V8_FUNC
#error "V8_FUNC must exist before including this file"
#endif

V8_FUNC(v8_config_enable_debugger)
V8_FUNC(v8_config_enable_gc_api)
V8_FUNC(v8_config_enable_multithreading)
V8_FUNC(v8_config_set_debugger_break_on_start)
V8_FUNC(v8_config_set_debugger_port)
V8_FUNC(v8_config_set_debugger_runtime_name)
V8_FUNC(v8_config_set_script_cache)
V8_FUNC(v8_config_set_task_runner)
V8_FUNC(v8_create_config)
V8_FUNC(v8_create_runtime)
V8_FUNC(v8_delete_config)
V8_FUNC(v8_delete_runtime)
V8_FUNC(v8_get_node_api_env)

#undef V8_FUNC
