declare_args() {
  # Sets -DV8JSI_ENABLE_INSPECTOR
  v8jsi_enable_inspector = true

  # Sets -DV8JSI_ENABLE_NODE_API
  v8jsi_enable_node_api = true
}

target("shared_library", "v8jsi") {
  sources = [
    "IsolateData.h",
    "MurmurHash.cpp",
    "MurmurHash.h",
    "V8JsiRuntime.cpp",
    "V8JsiRuntime_impl.h",
    "jsi/JSIDynamic.h",
    "jsi/decorator.h",
    "jsi/instrumentation.h",
    "jsi/jsi-inl.h",
    "jsi/jsi.cpp",
    "jsi/jsi.h",
    "jsi/jsilib-windows.cpp",
    "jsi/jsilib.h",
    "jsi/threadsafe.h",
    "public/ScriptStore.h",
    "public/V8JsiRuntime.h",
  ]

  if (v8jsi_enable_node_api) {
    sources += [
      "napi/env-inl.h",
      "napi/js_native_api_v8.cc",
      "napi/js_native_api_v8.h",
      "napi/js_native_api_v8_internals.h",
      "napi/util-inl.h",
      "napi/util.cc",
      "napi/v8_api.cpp",
      "node-api/js_native_api.h",
      "node-api/js_native_api_types.h",
      "node-api/js_runtime_api.h",
      "public/compat.h",
      "public/v8_api.h",
    ]
  }

  if (is_win) {
    sources += [
      "etw/tracing.cpp",
      "etw/tracing.h",
      "version_gen.rc",
    ]

    if (v8jsi_enable_inspector) {
      sources += [
        "inspector/inspector_agent.cpp",
        "inspector/inspector_agent.h",
        "inspector/inspector_socket.cpp",
        "inspector/inspector_socket.h",
        "inspector/inspector_socket_server.cpp",
        "inspector/inspector_socket_server.h",
        "inspector/inspector_tcp.cpp",
        "inspector/inspector_tcp.h",
        "inspector/inspector_utils.cpp",
        "inspector/inspector_utils.h",
        "inspector/llhttp.c",
        "inspector/llhttp.h",
        "inspector/llhttp_api.c",
        "inspector/llhttp_http.c",
      ]
    }

    ldflags = [
      "/OPT:REF",
      "/INCREMENTAL:NO",
    ]

    if (!is_clang) {
      ldflags += [
        "/PDBSTRIPPED:v8jsi_stripped.dll.pdb",
        "/SOURCELINK:" + rebase_path("//jsi/source_link_gen.json"),
      ]
    }
  } else if (!is_mac) {
    ldflags = [ "-Wl,--allow-multiple-definition" ]
    ldflags += [ "-Wl,--version-script=" + rebase_path("//jsi/makev8jsi.lst") ]
  }

  include_dirs = [
    ".",
    "../include",
    "jsi",
    "public",
    getenv("ASIO_ROOT"),
  ]

  if (v8jsi_enable_node_api) {
    include_dirs += [ "node-api" ]
  }

  configs += [
    "//:toolchain",
    "//:internal_config_base",
    "//build/config/compiler:exceptions",
  ]
  configs -= [ "//build/config/compiler:no_exceptions" ]

  if (is_win) {
    configs -= [ "//build/config/compiler:cet_shadow_stack" ]
    configs -= [ "//build/config/win:default_incremental_linking" ]
    configs += [ "//build/config/win:win_msvc_cfg" ]
  }

  deps = [
    "//:v8_headers",
    "//:v8_monolith",
  ]

  defines = [ "BUILDING_V8JSI_SHARED" ]

  if (is_win) {
    libs = [
      "dbghelp.lib",
      "bcrypt.lib",
      "shlwapi.lib",
      "winmm.lib",
    ]
  }

  if (v8jsi_enable_inspector) {
    defines += [ "V8JSI_ENABLE_INSPECTOR" ]
  }
}

target("executable", "jsitests") {
  testonly = true

  deps = [
    ":v8jsi",
    "//build/win:default_exe_manifest",
    "//testing/gtest",
  ]

  configs += [
    "//:toolchain",
    "//:internal_config_base",
    "//build/config/compiler:exceptions",
    "//build/config/compiler:rtti",
  ]
  configs -= [
    "//build/config/compiler:no_exceptions",
    "//build/config/compiler:no_rtti",
  ]

  cflags = [ "-DJSI_V8_IMPL" ]

  # Run microtasks explicitly for JSI
  cflags += [ "-DJSI_SUPPORT_MICROTASKS" ]

  include_dirs = [
    ".",
    "jsi",
    "public",
  ]

  if (v8jsi_enable_node_api) {
    include_dirs += [
      "napi/test",
      "node-api",
    ]
  }

  sources = [
    "jsi/JSIDynamic.h",
    "jsi/decorator.h",
    "jsi/instrumentation.h",
    "jsi/jsi-inl.h",
    "jsi/jsi.cpp",
    "jsi/jsi.h",
    "jsi/jsilib.h",
    "jsi/test/testlib.cpp",
    "jsi/test/testlib.h",
    "jsi/test/testlib_ext.cpp",
    "jsi/threadsafe.h",
    "public/compat.h",
    "public/v8_api.h",
    "testmain.cpp",
  ]

  if (is_win) {
    sources += [ "jsi/jsilib-windows.cpp" ]
  } else {
    sources += [ "jsi/jsilib-posix.cpp" ]
  }

  if (v8jsi_enable_node_api) {
    sources += [
      "node-api-jsi/ApiLoaders/JSRuntimeApi.cpp",
      "node-api-jsi/ApiLoaders/JSRuntimeApi.h",
      "node-api-jsi/ApiLoaders/JSRuntimeApi.inc",
      "node-api-jsi/ApiLoaders/NodeApi.cpp",
      "node-api-jsi/ApiLoaders/NodeApi.h",
      "node-api-jsi/ApiLoaders/NodeApi.inc",
      "node-api-jsi/ApiLoaders/V8Api.cpp",
      "node-api-jsi/ApiLoaders/V8Api.h",
      "node-api-jsi/ApiLoaders/V8Api.inc",
      "node-api-jsi/NodeApiJsiRuntime.cpp",
      "node-api-jsi/NodeApiJsiRuntime.h",
    ]

    if (is_win) {
      sources += [ "node-api-jsi/ApiLoaders/NodeApi_win.cpp" ]
    } else {
      sources += [ "node-api-jsi/ApiLoaders/NodeApi_posix.cpp" ]
    }
  }
}

# copy test JS files
copy("napi_test_js_files") {
  sources = [
    "napi/test/js-native-api/2_function_arguments/test.js",
    "napi/test/js-native-api/3_callbacks/test.js",
    "napi/test/js-native-api/4_object_factory/test.js",
    "napi/test/js-native-api/5_function_factory/test.js",
    "napi/test/js-native-api/6_object_wrap/test-object-wrap-ref.js",
    "napi/test/js-native-api/6_object_wrap/test.js",
    "napi/test/js-native-api/7_factory_wrap/test.js",
    "napi/test/js-native-api/8_passing_wrapped/test.js",
    "napi/test/js-native-api/common/assert.js",
    "napi/test/js-native-api/common/child_process.js",
    "napi/test/js-native-api/common/common.js",
    "napi/test/js-native-api/test_array/test.js",
    "napi/test/js-native-api/test_bigint/test.js",
    "napi/test/js-native-api/test_cannot_run_js/test.js",
    "napi/test/js-native-api/test_constructor/test.js",
    "napi/test/js-native-api/test_constructor/test2.js",
    "napi/test/js-native-api/test_constructor/test_null.js",
    "napi/test/js-native-api/test_conversions/test.js",
    "napi/test/js-native-api/test_dataview/test.js",
    "napi/test/js-native-api/test_date/test.js",
    "napi/test/js-native-api/test_error/test.js",
    "napi/test/js-native-api/test_exception/test.js",
    "napi/test/js-native-api/test_exception/testFinalizerException.js",
    "napi/test/js-native-api/test_finalizer/test.js",
    "napi/test/js-native-api/test_finalizer/test_fatal_finalize.js",
    "napi/test/js-native-api/test_function/test.js",
    "napi/test/js-native-api/test_general/test.js",
    "napi/test/js-native-api/test_general/testEnvCleanup.js",
    "napi/test/js-native-api/test_general/testFinalizer.js",
    "napi/test/js-native-api/test_general/testGlobals.js",
    "napi/test/js-native-api/test_general/testInstanceOf.js",
    "napi/test/js-native-api/test_general/testNapiRun.js",
    "napi/test/js-native-api/test_general/testNapiStatus.js",
    "napi/test/js-native-api/test_handle_scope/test.js",
    "napi/test/js-native-api/test_instance_data/test.js",
    "napi/test/js-native-api/test_new_target/test.js",
    "napi/test/js-native-api/test_number/test.js",
    "napi/test/js-native-api/test_number/test_null.js",
    "napi/test/js-native-api/test_object/test.js",
    "napi/test/js-native-api/test_object/test_exceptions.js",
    "napi/test/js-native-api/test_object/test_null.js",
    "napi/test/js-native-api/test_promise/test.js",
    "napi/test/js-native-api/test_properties/test.js",
    "napi/test/js-native-api/test_reference/test.js",
    "napi/test/js-native-api/test_reference/test_finalizer.js",
    "napi/test/js-native-api/test_reference_double_free/test.js",
    "napi/test/js-native-api/test_reference_double_free/test_wrap.js",
    "napi/test/js-native-api/test_string/test.js",
    "napi/test/js-native-api/test_string/test_null.js",
    "napi/test/js-native-api/test_symbol/test1.js",
    "napi/test/js-native-api/test_symbol/test2.js",
    "napi/test/js-native-api/test_symbol/test3.js",
    "napi/test/js-native-api/test_typedarray/test.js",
  ]
  outputs = [ "$root_out_dir/{{source}}" ]
}

_js_test_root = "napi/test/js-native-api"

config("test_module") {
  include_dirs = [
    "node-api",
    "napi/test/js-native-api",
  ]
  if (is_win) {
    # Import Node-API functions and (-FC) use full path of source code files in diagnostics.
    cflags = [
      "-DNAPI_EXTERN=__declspec(dllimport)",
      "-FC",
    ]
  }
}

loadable_module("2_function_arguments") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/2_function_arguments/2_function_arguments.c" ]
}

loadable_module("3_callbacks") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/3_callbacks/3_callbacks.c" ]
}

loadable_module("4_object_factory") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/4_object_factory/4_object_factory.c" ]
}

loadable_module("5_function_factory") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/5_function_factory/5_function_factory.c" ]
}

loadable_module("6_object_wrap") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/6_object_wrap/6_object_wrap.cc" ]
}

loadable_module("7_factory_wrap") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [
    "$_js_test_root/7_factory_wrap/7_factory_wrap.cc",
    "$_js_test_root/7_factory_wrap/myobject.cc",
  ]
}

loadable_module("8_passing_wrapped") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [
    "$_js_test_root/8_passing_wrapped/8_passing_wrapped.cc",
    "$_js_test_root/8_passing_wrapped/myobject.cc",
  ]
}

loadable_module("test_array") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_array/test_array.c" ]
}

loadable_module("test_bigint") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_bigint/test_bigint.c" ]
}

loadable_module("test_cannot_run_js") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  defines = [ "NAPI_EXPERIMENTAL" ]
  sources = [ "$_js_test_root/test_cannot_run_js/test_cannot_run_js.c" ]
}

loadable_module("test_pending_exception") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  defines = [ "NAPI_VERSION=8" ]
  sources = [ "$_js_test_root/test_cannot_run_js/test_cannot_run_js.c" ]
}

loadable_module("test_constructor") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [
    "$_js_test_root/test_constructor/test_constructor.c",
    "$_js_test_root/test_constructor/test_null.c",
  ]
}

loadable_module("test_conversions") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [
    "$_js_test_root/test_conversions/test_conversions.c",
    "$_js_test_root/test_conversions/test_null.c",
  ]
}

loadable_module("test_dataview") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_dataview/test_dataview.c" ]
}

loadable_module("test_date") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_date/test_date.c" ]
}

loadable_module("test_error") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_error/test_error.c" ]
}

loadable_module("test_exception") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_exception/test_exception.c" ]
}

loadable_module("test_finalizer") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  defines = [ "NAPI_EXPERIMENTAL" ]
  sources = [ "$_js_test_root/test_finalizer/test_finalizer.c" ]
}

loadable_module("test_function") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_function/test_function.c" ]
}

loadable_module("test_general") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_general/test_general.c" ]
}

loadable_module("test_handle_scope") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_handle_scope/test_handle_scope.c" ]
}

loadable_module("test_instance_data") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_instance_data/test_instance_data.c" ]
}

loadable_module("test_new_target") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_new_target/test_new_target.c" ]
}

loadable_module("test_number") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [
    "$_js_test_root/test_number/test_null.c",
    "$_js_test_root/test_number/test_number.c",
  ]
}

loadable_module("test_object") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [
    "$_js_test_root/test_object/test_null.c",
    "$_js_test_root/test_object/test_object.c",
  ]
}

loadable_module("test_exceptions") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_object/test_exceptions.c" ]
}

loadable_module("test_promise") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_promise/test_promise.c" ]
}

loadable_module("test_properties") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_properties/test_properties.c" ]
}

loadable_module("test_reference") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_reference/test_reference.c" ]
}

loadable_module("test_ref_finalizer") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_reference/test_finalizer.c" ]
}

loadable_module("test_reference_double_free") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [
    "$_js_test_root/test_reference_double_free/test_reference_double_free.c",
  ]
}

loadable_module("test_string") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  defines = [ "NAPI_EXPERIMENTAL" ]
  sources = [
    "$_js_test_root/test_string/test_null.c",
    "$_js_test_root/test_string/test_string.c",
  ]
}

loadable_module("test_symbol") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_symbol/test_symbol.c" ]
}

loadable_module("test_typedarray") {
  configs += [ ":test_module" ]
  deps = [ ":v8jsi" ]
  sources = [ "$_js_test_root/test_typedarray/test_typedarray.c" ]
}

target("executable", "node_api_tests") {
  testonly = true

  deps = [
    ":2_function_arguments",
    ":3_callbacks",
    ":4_object_factory",
    ":5_function_factory",
    ":6_object_wrap",
    ":7_factory_wrap",
    ":8_passing_wrapped",
    ":napi_test_js_files",
    ":test_array",
    ":test_bigint",
    ":test_cannot_run_js",
    ":test_constructor",
    ":test_conversions",
    ":test_dataview",
    ":test_date",
    ":test_error",
    ":test_exception",
    ":test_exceptions",
    ":test_finalizer",
    ":test_function",
    ":test_general",
    ":test_handle_scope",
    ":test_instance_data",
    ":test_new_target",
    ":test_number",
    ":test_object",
    ":test_pending_exception",
    ":test_promise",
    ":test_properties",
    ":test_ref_finalizer",
    ":test_reference",
    ":test_reference_double_free",
    ":test_string",
    ":test_symbol",
    ":test_typedarray",
    ":v8jsi",
    "//build/win:default_exe_manifest",
    "//testing/gtest",
  ]

  configs += [
    "//:toolchain",
    "//:internal_config_base",
    "//build/config/compiler:exceptions",
    "//build/config/compiler:rtti",
  ]
  configs -= [
    "//build/config/compiler:no_exceptions",
    "//build/config/compiler:no_rtti",
  ]

  cflags = [ "-DJSI_V8_IMPL" ]

  # Run microtasks explicitly for JSI
  cflags += [ "-DJSI_SUPPORT_MICROTASKS" ]

  if (is_win) {
    # Import Node-API functions and (-FC) use full path of source code files in diagnostics.
    cflags += [
      "-DNAPI_EXTERN=__declspec(dllimport)",
      "-FC",
    ]
  }

  include_dirs = [
    ".",
    "napi",
    "napi/test",
    "node-api",
    "public",
  ]

  sources = [
    "napi/test/child_process.cpp",
    "napi/test/child_process.h",
    "napi/test/node_api_test.cpp",
    "napi/test/node_api_test.h",
    "napi/test/node_api_test_v8.cpp",
    "napi/test/testmain.cpp",
    "node-api/js_native_api.h",
    "node-api/js_native_api_types.h",
    "node-api/js_runtime_api.h",
    "public/compat.h",
    "public/v8_api.h",
  ]
}
